baseURL = "https://jameson-mcghee.github.io/RancherQASpace/"
languageCode = "en-us"
title = "Rancher QA Space"
theme = "gohugo-theme-ananke"

[Menu]
    [[Menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[Menu.main]]
        name = "About"
        url = "/about/"
        weight = 2
    [[Menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 3
    [[Menu.main]]
        name = "Tags"
        url = "/tags/"
        weight = 4
    [[Menu.main]]
        name = "Categories"
        url = "/categories/"
        weight = 5
    [[Menu.main]]
        name = "Archives"
        url = "/archives/"
        weight = 6

[params]
    description = "This is a blog space for members of the Rancher Quality Assurance team to be able to post public blog posts about the Rancher Project and associated topics."
    favicon = "avatar.jpg"
    site_logo = "avatar.jpg"
    text_color = ""
    background_color_class = "bg-green"
    recent_posts_number = 3


[[params.ananke_socials]]
name = "github"
url = "https://github.com/rancher/"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/Rancher_Labs"

[[params.ananke_socials]]
name = "rancherdocs"
url = "https://rancher.com/docs/rancher/v2.x/en/"
label = "Rancher Docs"